### ISSUE TITLE
Common Data Service actions keep hardcoded environment

### ISSUE THREAD

**Issue by Costin-hcl** [jeffhollan/LogicAppTemplateCreator#99]
When exporting a Logic App with a CDS action, the action keeps its "path" property hardcoded:

         "path": "/v2/datasets/@{encodeURIComponent(encodeURIComponent('orgdXXXXXX.crm4'))}/tables/@{encodeURIComponent(encodeURIComponent('cdm_table'))}/items/@{encodeURIComponent(encodeURIComponent(triggerBody()?['empNumber']))}"

This is very hard to de-hardcode especially is a workflow expression is used - we need to add an apostrophe ARM parameter and concatenate to the formula.

**Comment by MLogdberg** [comment]
Thanks for reporting this, it should be solved by PR #100, please take a look and test it out.

**Comment by Costin-hcl** [comment]
@MLogdberg  - I do see some change but the path is still not added as a parameter. Here is what I got from a CDS action:
 
  "Get_Contact_Name": {
                  "runAfter": {
                    "Condition": [
                      "Succeeded"
                    ]
                  },
                  "type": "ApiConnection",
                  "inputs": {
                    "host": {
                      "connection": {
                        "name": "@parameters('$connections')['commondataservice']['connectionId']"
                      }
                    },
                    "method": "get",
                    "path": "/v2/datasets/oXXXXXXXXXXXXXX.crm/tables/contacts/items/@{variables('contactId')}"
                  }
                },

The path property still has /v2/datasets/oXXXXXXXXXXXXXX.crm/ hard-coded. I was using the binary though, did a Update-Module LogicAppTemplate. How can I check the version does it have a command line argument?

**Comment by MLogdberg** [comment]
Looks like it might be missing this type of action I'll take a look

**Comment by MLogdberg** [comment]
Hi, 

I've tried almost all actions, here is a sample of Get Record:
`
   "Get_record": {
              "runAfter": {
                "Create_a_new_record": [
                  "Succeeded"
                ]
              },
              "type": "ApiConnection",
              "inputs": {
                "host": {
                  "connection": {
                    "name": "@parameters('$connections')['commondataservice_1']['connectionId']"
                  }
                },
                "method": "get",
                "path": "[concat('/v2/datasets/@{encodeURIComponent(encodeURIComponent(', parameters('__apostrophe'), parameters('Get_record-environment'), parameters('__apostrophe'), '))}/tables/@{encodeURIComponent(encodeURIComponent(''cdmtmp_accountcontacts''))}/items/@{encodeURIComponent(encodeURIComponent(variables(''myId'')))}')]"
              }
            },
`

Are you sure you are running the latest version?
Here is my version runnig:
`
PS C:\temp\ARMTemplateGenerators> Get-Module LogicAppTemplate
ModuleType Version    Name                                ExportedCommands                                                                                                                  
---------- -------    ----                                ----------------                                                                                                                  
Binary     0.1.4.0    LogicAppTemplate                    {Get-EmptyParameterTemplate, Get-CustomConnectorTemplate, Get-IntegrationAccountSchemaTemplate, Get-IntegrationAccountMapTempla...
`

**Comment by Costin-hcl** [comment]
@MLogdberg  - I did say it was working with the new version - later edit. Initially, I tried Update-Module and this probably didn't update. So then I just got the latest version from GitHub, built the DLL, imported it from the local debug folder and tested. The changes work well now, they just need to be published.

Many thanks!

**Comment by MLogdberg** [comment]
Ahh sorry my bad for bad reading, awesome it works! 👍 Closing this issue now.
